{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/unknownError"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/asyncmoya\/dataerror\/unknownerror"]}],"metadata":{"modules":[{"name":"AsyncMoya"}],"externalID":"s:9AsyncMoya9DataErrorO07unknownD0yA2CmF","title":"DataError.unknownError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"role":"symbol","roleHeading":"Case","symbolKind":"case"},"abstract":[{"text":"그 외 알 수 없는 오류 상황을 처리할 때 사용합니다.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://AsyncMoya/documentation/AsyncMoya":{"abstract":[{"type":"text","text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리"}],"kind":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","title":"AsyncMoya","role":"collection","type":"topic","url":"\/documentation\/asyncmoya"},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"abstract":[{"text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형","type":"text"}],"title":"DataError","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataError","kind":"identifier"}],"navigatorTitle":[{"text":"DataError","kind":"identifier"}],"url":"\/documentation\/asyncmoya\/dataerror","kind":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"},"doc://AsyncMoya/documentation/AsyncMoya/DataError/unknownError":{"type":"topic","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/unknownError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"abstract":[{"type":"text","text":"그 외 알 수 없는 오류 상황을 처리할 때 사용합니다."}],"title":"DataError.unknownError","role":"symbol","url":"\/documentation\/asyncmoya\/dataerror\/unknownerror","kind":"symbol"}}}