{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/unknownError"},"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/asyncmoya\/dataerror\/unknownerror"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","modules":[{"name":"AsyncMoya"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"title":"DataError.unknownError","externalID":"s:9AsyncMoya9DataErrorO07unknownD0yA2CmF"},"abstract":[{"type":"text","text":"그 외 알 수 없는 오류 상황을 처리할 때 사용합니다."}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://AsyncMoya/documentation/AsyncMoya":{"url":"\/documentation\/asyncmoya","type":"topic","title":"AsyncMoya","abstract":[{"type":"text","text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리"}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","kind":"symbol","role":"collection"},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataError","kind":"identifier"}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError","abstract":[{"type":"text","text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형"}],"navigatorTitle":[{"text":"DataError","kind":"identifier"}],"url":"\/documentation\/asyncmoya\/dataerror","type":"topic","kind":"symbol","title":"DataError","role":"symbol"},"doc://AsyncMoya/documentation/AsyncMoya/DataError/unknownError":{"abstract":[{"text":"그 외 알 수 없는 오류 상황을 처리할 때 사용합니다.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/asyncmoya\/dataerror\/unknownerror","title":"DataError.unknownError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/unknownError","kind":"symbol"}}}